- name: Running Windows Tasks
  hosts: windows
  vars:
    Ansisble_port: 5986
    Ansible_user: 
    Ansisble_winrm_server_cert_validation: ignore
    Ansisble_winrm_transport: ntlm
  tasks:
    - name: Name: PowerShell_Gatherer
      register: output 
      win_command: >
        powershell.exe -Sta -Nop -Command "IEX(IWR 'https://raw.githubusercontent.com/JonBauer123/csec465_lab4/master/scripts/ps_gather.ps1' -UseBasicParsing)"
    - name: Print Output
      debug: 
        msg: 
           - "Output: {{ PowerShell_Gatherer.stdout }}"
